### ISSUE TITLE
Error logging into Memrise

### ISSUE THREAD

**Issue by MikeOWave** [wilddom/memrise2anki-extension#103]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-11 16:34:55

Caught exception:
Traceback (most recent call last):
  File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\importer.py", line 210, in accept
    if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()):
  File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\memrise.py", line 773, in login
    for field in form.find_all("input"):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by MikeOWave** [comment]
I tried with both the current version of Anki and older ones, but always got this same result.

**Comment by MikeOWave** [comment]
I would be curious to know if this issue is affecting everybody or just Windows users? I could borrow a Mac if I knew it would work on one.

**Comment by Quezako** [comment]
last update is 8 month ago, so it's probably outdated with the latest Memrise modifications.

**Comment by wilddom** [comment]
Still working fine on Linux

**Comment by MikeOWave** [comment]
Thanks for the tip. I'll see if I can figure out how to run Linux on my computer.

**Comment by barolo** [comment]
Also fails on Linux now, with  Anki 2.1.49

**Comment by wilddom** [comment]
> Also fails on Linux now, with Anki 2.1.49

Can't confirm, still works here with the mentioned version.

**Comment by barolo** [comment]
> > Also fails on Linux now, with Anki 2.1.49
> 
> Can't confirm, still works here with the mentioned version.

Just switched to realmayus fork which fixed login issues on all my devices [macOS and Linux]

**Comment by Quezako** [comment]
> > > Also fails on Linux now, with Anki 2.1.49
> > 
> > 
> > Can't confirm, still works here with the mentioned version.
> 
> Just switched to realmayus fork which fixed login issues on all my devices [macOS and Linux]

I confirm that the realmayus fork is working with Anki 2.1.46 under Windows 11.

**Comment by wilddom** [comment]
Good to know

**Comment by congbinh21** [comment]
Hi, today is December 5th, 2021, and I've just run that add-on. It doesn't work. The announcement is the same as that. 
First like this 
![image](https://user-images.githubusercontent.com/95559114/144734987-04ddc3da-5e0e-44c8-8e60-350ac8291a43.png)
then I chose "oke", then "oke" and like this
![image](https://user-images.githubusercontent.com/95559114/144735002-5b6b6aa8-ee23-4a37-9d0f-ddcb05e0929c.png)
I tried changing another laptop, but it still doesn't work. 
Please, help me.
Thank you



> Error An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site. Debug info: Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2021-10-11 16:34:55
> 
> Caught exception: Traceback (most recent call last): File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\importer.py", line 210, in accept if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()): File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\memrise.py", line 773, in login for field in form.find_all("input"): AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by gustavklopp** [comment]
> Hi, today is December 5th, 2021, and I've just run that add-on. It doesn't work. The announcement is the same as that. First like this ![image](https://user-images.githubusercontent.com/95559114/144734987-04ddc3da-5e0e-44c8-8e60-350ac8291a43.png) then I chose "oke", then "oke" and like this ![image](https://user-images.githubusercontent.com/95559114/144735002-5b6b6aa8-ee23-4a37-9d0f-ddcb05e0929c.png) I tried changing another laptop, but it still doesn't work. Please, help me. Thank you
> 
> > Error An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site. Debug info: Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2021-10-11 16:34:55
> > Caught exception: Traceback (most recent call last): File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\importer.py", line 210, in accept if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()): File "C:\Users\danno\AppData\Roaming\Anki2\addons21\2071525018\memrise.py", line 773, in login for field in form.find_all("input"): AttributeError: 'NoneType' object has no attribute 'find_all'

I didn't check what was changed in that fork but I can confirm that the fork from @realmayus is working: https://github.com/realmayus/memrise2anki-extension

**Comment by wilddom** [comment]
At the moment I have no need to use the addon myself, but I hope to find a few minutes over the holidays to take a closer look.

**Comment by wilddom** [comment]
Please try the [1.2.7](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.7) release.
